---
# tasks file for roles/get_securityGroup_us_east_1

- name: Include vars of resources.yml
  include_vars:
    file: vars/resources.yml
    name: resources

- name: Include vars of dynamic.yml
  include_vars:
    file: vars/dynamic.yml
    name: dynamic

- name: Get Security Group in {{resources.region}}
  ec2_group_facts:
    profile: "{{resources.profile}}"
    region: "{{resources.region}}"
    filters:
      "tag:Name": "{{resources.sg_default_name_us_east_1}}"
  register: sg_data

- name: Clean Security Group id into dynamic file
  lineinfile:
   state: absent
   dest: "{{resources.var_dynamic_file}}"
   regexp: "{{ item.tags.Name }}"
  with_items: "{{sg_data.security_groups}}"

- name: Write Security Group id to dynamic file
  lineinfile:
   state: present
   dest: "{{resources.var_dynamic_file}}"
   line: '{{ item.tags.Name }}: {{ item.group_id }}'
  with_items: "{{sg_data.security_groups}}"