#playbook SUBNET
---
- hosts: localhost
  connection: local
  gather_facts: False

  roles:
      # Configuracao Security Group
      - set_securityGroup_us_east_1
      - get_securityGroup_us_east_1
