#playbook VPC
---
- hosts: localhost
  connection: local
  gather_facts: False

  roles:
      # Configuracao da VPC
      - set_vpc_us_east_1
      - get_vpc_us_east_1
      # Configuracao do IGW associado a VPC previamente configurada
      - set_igw_us_east_1
      - get_igw_us_east_1