---
# tasks file for roles/get_subnet_us_east_1

- name: Include vars of resources.yml
  include_vars:
    file: vars/resources.yml
    name: resources

- name: Include vars of dynamic.yml
  include_vars:
    file: vars/dynamic.yml
    name: dynamic

- name: Get Subnet in {{resources.region}}
  ec2_vpc_subnet_facts:
    profile: "{{resources.profile}}"
    region: "{{resources.region}}"
    filters:
      vpc-id: "{{dynamic.vpc_nv_desafio}}"
  register: subnet_data

- name: Clean Subnets id into dynamic file
  lineinfile:
   state: absent
   dest: "{{resources.var_dynamic_file}}"
   regexp: "{{ item.tags.Name }}"
  with_items: "{{subnet_data.subnets}}"

- name: Write Subnets id to dynamic file
  lineinfile:
   state: present
   dest: "{{resources.var_dynamic_file}}"
   line: '{{ item.tags.Name }}: {{ item.id }}'
  with_items: "{{subnet_data.subnets}}"